export const ANIMAL_CREATE_REQUEST = 'ANIMAL_CREATE_REQUEST';
export const ANIMAL_CREATE_SUCCESS = 'ANIMAL_CREATE_SUCCESS';
export const ANIMAL_CREATE_FAIL = 'ANIMAL_CREATE_FAIL';

export const ANIMAL_DETAILS_REQUEST = 'ANIMAL_DETAILS_REQUEST';
export const ANIMAL_DETAILS_SUCCESS = 'ANIMAL_DETAILS_SUCCESS';
export const ANIMAL_DETAILS_FAIL = 'ANIMAL_DETAILS_FAIL';
export const ANIMAL_DETAILS_RESET = 'ANIMAL_DETAILS_RESET';

export const ANIMAL_LIST_REQUEST = 'ANIMAL_LIST_REQUEST';
export const ANIMAL_LIST_SUCCESS = 'ANIMAL_LIST_SUCCESS';
export const ANIMAL_LIST_FAIL = 'ANIMAL_LIST_FAIL';

export const ANIMALS_AVAILABLE_REQUEST = 'ANIMALS_AVAILABLE_REQUEST';
export const ANIMALS_AVAILABLE_SUCCESS = 'ANIMALS_AVAILABLE_SUCCESS';
export const ANIMALS_AVAILABLE_FAIL = 'ANIMALS_AVAILABLE_FAIL';

export const ANIMALS_SCHEDULED_REQUEST = 'ANIMALS_SCHEDULED_REQUEST';
export const ANIMALS_SCHEDULED_SUCCESS = 'ANIMALS_SCHEDULED_SUCCESS';
export const ANIMALS_SCHEDULED_FAIL = 'ANIMALS_SCHEDULED_FAIL';

export const ANIMAL_UPDATE_REQUEST = 'ANIMAL_UPDATE_REQUEST';
export const ANIMAL_UPDATE_SUCCESS = 'ANIMAL_UPDATE_SUCCESS';
export const ANIMAL_UPDATE_FAIL = 'ANIMAL_UPDATE_FAIL';
export const ANIMAL_UPDATE_RESET = 'ANIMAL_UPDATE_RESET';

export const ANIMAL_DELETE_REQUEST = 'ANIMAL_DELETE_REQUEST';
export const ANIMAL_DELETE_SUCCESS = 'ANIMAL_DELETE_SUCCESS';
export const ANIMAL_DELETE_FAIL = 'ANIMAL_DELETE_FAIL';
export const ANIMAL_DELETE_RESET = 'ANIMAL_DELETE_RESET';

export const ANIMAL_ADDRESS_MAP_CONFIRM = 'ANIMAL_ADDRESS_MAP_CONFIRM';