export const SHELTER_CREATE_REQUEST = 'SHELTER_CREATE_REQUEST';
export const SHELTER_CREATE_SUCCESS = 'SHELTER_CREATE_SUCCESS';
export const SHELTER_CREATE_FAIL = 'SHELTER_CREATE_FAIL';

export const SHELTER_DETAILS_REQUEST = 'SHELTER_DETAILS_REQUEST';
export const SHELTER_DETAILS_SUCCESS = 'SHELTER_DETAILS_SUCCESS';
export const SHELTER_DETAILS_FAIL = 'SHELTER_DETAILS_FAIL';
export const SHELTER_DETAILS_RESET = 'SHELTER_DETAILS_RESET';

export const SHELTER_VIEW_REQUEST = 'SHELTER_VIEW_REQUEST';
export const SHELTER_VIEW_SUCCESS = 'SHELTER_VIEW_SUCCESS';
export const SHELTER_VIEW_FAIL = 'SHELTER_VIEW_FAIL';

export const SHELTER_LIST_REQUEST = 'SHELTER_LIST_REQUEST';
export const SHELTER_LIST_SUCCESS = 'SHELTER_LIST_SUCCESS';
export const SHELTER_LIST_FAIL = 'SHELTER_LIST_FAIL';

export const SHELTER_UPDATE_REQUEST = 'SHELTER_UPDATE_REQUEST';
export const SHELTER_UPDATE_SUCCESS = 'SHELTER_UPDATE_SUCCESS';
export const SHELTER_UPDATE_FAIL = 'SHELTER_UPDATE_FAIL';
export const SHELTER_UPDATE_RESET = 'SHELTER_UPDATE_RESET';

export const SHELTER_DELETE_REQUEST = 'SHELTER_DELETE_REQUEST';
export const SHELTER_DELETE_SUCCESS = 'SHELTER_DELETE_SUCCESS';
export const SHELTER_DELETE_FAIL = 'SHELTER_DELETE_FAIL';
export const SHELTER_DELETE_RESET = 'SHELTER_DELETE_RESET';

export const SHELTER_ADDRESS_MAP_CONFIRM = 'SHELTER_ADDRESS_MAP_CONFIRM';